---
output: word_document
---
```{r}
hpog <- read.csv(file= "C:/Users/xchai/Desktop/HPOG_ClassStudents_R.csv", head=TRUE)
#summary(hpog)
#names(hpog)
#sort data by ascending 'case' and descending 'TIME'
attach(hpog)
hpog.sort <- hpog[order(case, -TIME),]
#hpog.sort[1:10,1:6]
h2<-hpog.sort[!duplicated(hpog.sort$case),]
#h2[1:10,1:6]
```

**Create new variable: dropstatus**
```{r}
#Method 1-didn't work.
#h2$dropstatus[h2$status=0]<-1
#h2$dropstatus[h2$status=1 or status=2]<-0
#h2[,1:6]

#Method 2-works!
h2$dropstatus <- ifelse(h2$STATUS==0, 1, 0)
h2[1:10, 100:110]
```

**create mean of EB and EH with some items removed per Dr. Hong's request**
```{r}
h2$EBmean<-rowMeans(subset(h2,select=c(EB1:EB4,EB6,EB8,EB10:EB13,EB15:EB19,EB22:EB26)),na.rm=TRUE)
head(h2$EBmean)

h2$EHmean<-rowMeans(subset(h2,select=c(EH3:EH6,EH11,EH15,EH17:EH24)),na.rm=TRUE)
head(h2$EHmean)
```

**logistic regression of dropout on EBmean and EHmean **
```{r}
logisticmod1<-glm(dropstatus~EBmean+EHmean,family=binomial(logit),data=h2)
summary(logisticmod1)
```

**CPH model (time till Drop-out) on EBmean and EHmean**
```{r}
#aggregate--works!
maxdate<-aggregate(as.Date(hpog.sort$DATE,"%d-%b-%Y"),by=list(hpog.sort$case),FUN=max,na.rm=TRUE)
head(maxdate)
#maxdate[1:5,]

mindate<-aggregate(as.Date(hpog.sort$DATE,"%d-%b-%Y"),by=list(hpog.sort$case),FUN=min,na.rm=TRUE)
head(mindate)

#add datediff column into h2 
case<-c(maxdate[,1])
max.minus.min<-c(maxdate[,2]-mindate[,2])
date<-data.frame(case,max.minus.min)
#date[1:50,]

h3<-merge(h2,date,by="case")
names(h3)
h3$max.minus.min[1:30]
```
**Fit CPH model on EBmean and EHmean**
```{r}
library(survival)
#efron or breslow?
CPHmod1<-coxph(Surv(max.minus.min,dropstatus==1)~EBmean+EHmean,ties="breslow",data=h3)
summary(CPHmod1)

```

**regrouping EB and EH**
```{r}
h2$EB1mean<-rowMeans(subset(h2,select=c(EB10:EB13)),na.rm=TRUE)
h2$EB2mean<-rowMeans(subset(h2,select=c(EB15:EB17)),na.rm=TRUE)
h2$EB3mean<-rowMeans(subset(h2,select=c(EB6,EB18:EB19)),na.rm=TRUE)
h2$EB4mean<-rowMeans(subset(h2,select=c(EB1:EB4,EB8)),na.rm=TRUE)
h2$EB5mean<-rowMeans(subset(h2,select=c(EB22:EB26)),na.rm=TRUE)
h2$EH1mean<-rowMeans(subset(h2,select=c(EH3:EH6)),na.rm=TRUE)
h2$EH2mean<-rowMeans(subset(h2,select=c(EH11,EH15)),na.rm=TRUE)
h2$EH3mean<-rowMeans(subset(h2,select=c(EH17:EH20)),na.rm=TRUE)
h2$EH4mean<-rowMeans(subset(h2,select=c(EH21:EH24)),na.rm=TRUE)
```



**Logistic model with separated EBmean and EHmean**
```{r}
logisticmod2<-glm(dropstatus~EB1mean+EB2mean+EB3mean+EB4mean+EB5mean+EH1mean+EH2mean+EH3mean+EH4mean,family=binomial(logit),data=h2)
summary(logisticmod2)
```

**CPH model with separated EBmean and EHmean**
```{r}
#aggregate--works!
maxdate<-aggregate(as.Date(hpog.sort$DATE,"%d-%b-%Y"),by=list(hpog.sort$case),FUN=max,na.rm=TRUE)
head(maxdate)
#maxdate[1:5,]

mindate<-aggregate(as.Date(hpog.sort$DATE,"%d-%b-%Y"),by=list(hpog.sort$case),FUN=min,na.rm=TRUE)
head(mindate)

#add datediff column into h2 
case<-c(maxdate[,1])
max.minus.min<-c(maxdate[,2]-mindate[,2])
date<-data.frame(case,max.minus.min)
#date[1:50,]

h3<-merge(h2,date,by="case")
names(h3)
#h3$max.minus.min[1:30]
library(survival)
CPHmod2<-coxph(Surv(max.minus.min,dropstatus==1)~EB1mean+EB2mean+EB3mean+EB4mean+EB5mean+EH1mean+EH2mean+EH3mean+EH4mean,ties="breslow",data=h3)
summary(CPHmod2)

```




